# Generated by Django 4.1.7 on 2023-03-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
