# Generated by Django 4.1.7 on 2023-04-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0003_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("EXPIRED", "Expired"),
                ],
                max_length=7,
            ),
        ),
    ]
