# Generated by Django 4.1.7 on 2023-04-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0004_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.CharField(max_length=500),
        ),
    ]
