# Generated by Django 4.1.7 on 2023-04-13 13:09

from django.db import migrations
from django.db.migrations import RunPython


def func(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "fixture_data.json")


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0006_alter_payment_session_id_alter_payment_session_url"),
        ("sessions", "0001_initial"),
        ("django_celery_beat", "0018_improve_crontab_helptext"),
    ]

    operations = [RunPython(func, reverse_func)]
